# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solveHVQCD <- function(xi, ti, V0, W0, lambda0) {
    .Call('_HVQCD_solveHVQCD', PACKAGE = 'HVQCD', xi, ti, V0, W0, lambda0)
}

