# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solveHVQCD <- function(xi = 1L, ti = 1L, W0 = 12/11.0, V0 = 12L, lambda0 = 8 * M_PI * M_PIL) {
    .Call('_HVQCD_solveHVQCD', PACKAGE = 'HVQCD', xi, ti, W0, V0, lambda0)
}

